root = "."
tmp_dir = "tmp"

[build]
entrypoint = "./tmp/honk"
args_bin = [ "" ]
cmd = 'go build -o honk -ldflags="-X main.version=0.0.1 -X main.commit=5d202616f60be31c3a54e8d9145096a3d752595f -X main.date=2025-12-29T13:37:56Z" -o ./tmp/honk .'
exclude_dir = [ "assets", "tmp", "vendor", "client", "test", "resources", "config", "data" ]
include_ext = [ "go", "tpl", "tmpl", "html", "css", "js", "jsx", "ts", "tsx" ]

[color]
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[misc]
clean_on_exit = true
