root = "."
tmp_dir = "tmp"

[build]
entrypoint = "./tmp/honk"
args_bin = [ "" ]
cmd = 'go build -o honk -ldflags="-X main.version=0.0.0 -X main.commit=ead2d7830add26d53ecab3c907a290f0cdc1e078 -X main.date=2025-04-11T13:37:56Z" -o ./tmp/honk .'
exclude_dir = [ "assets", "tmp", "vendor", "client", "test", "resources", "config", "data" ]
include_ext = [ "go", "tpl", "tmpl", "html", "css", "js", "jsx", "ts", "tsx" ]

[color]
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[misc]
clean_on_exit = true
